workspace = { members = [ "mnist", "nn_lib"] }

[package]
name = "nn_from_scratch"
version = "0.1.0"
edition = "2021"
authors = ["Adrien Pelfresne", "Alexis Vapaille"]

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
pretty_env_logger = "0.5.0"
nn_lib = {path = "./nn_lib/"}
mnist = {path = "./mnist/"}
anyhow = "1.0.83"
log = "0.4.21"
image = "0.25.1"
# ndarray = {version = "0.15.6", features = ["matrixmultiply-threading", "rayon", "blas"]}
ndarray = {version = "0.15.6", features = ["matrixmultiply-threading", "rayon"]}
tokio = { version = "1.0", features = ["full"] }
tokio-tungstenite = "0.23"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
futures-util = "0.3"
hyper = { version = "1.0", features = ["full"] }
hyper-util = { version = "0.1", features = ["full"] }
http-body-util = "0.1"
hyper-tungstenite = "0.14"

[profile.release]
debug = true
